### ISSUE TITLE
Add MVA/MRVA

### ISSUE THREAD

**Issue by AlexSkeleton12** [IVAO-US/SectorFiles#3]
**Is your feature request related to a problem? Please describe.**
A missing necessity.

**Describe the solution you'd like**
Add MVA/MRVA

**Describe alternatives you've considered**
None other than painstakingly trying to go off of MRVA charts by themselves.

**Comment by wes-sleeman** [comment]
MRVAs are actually in the dataset. They were removed from the last couple while I fix the labelling for them. They'll be included again (now with better labels) in the next push.

**Comment by wes-sleeman** [comment]
Resolved as of https://github.com/IVAO-US/SectorGenerator/commit/e3ded729cda8f6cc93bcfa224ea052fbe08598ca.
Data available in ca47d74 (master).

**Comment by wes-sleeman** [comment]
![image](https://github.com/IVAO-US/SectorFiles/assets/9663827/011a5441-e83f-4209-8df3-da0c39cab4b3)
