### ISSUE TITLE
GEO Lines for Gates (PIER) are labeled TAXIWAY_CENTER

### ISSUE THREAD

**Issue by ttreaster** [IVAO-US/SectorFiles#5]
Gates Labels are correct.  However, PIER lines are labeled TAXI_CENTER in the <airport>.geo file.  Unable to assign a pier line color that is  not the same as "Taxiway Centerlines" in color file.  Should be "Gates Parking Stands" which assign color to Gates labeled and Stands (pier).

**Comment by wes-sleeman** [comment]
This is an enhancement request (additional functionality to have separate colours for different kinds of centrelines). Retagged accordingly.

**Comment by ttreaster** [comment]
No, not an enhancement request. It is the way it used to be. :-)
